export const THEMES = {
  classic: {
    name: 'Classic Americana',
    bg: '#f4f0e8',
    surface: '#ffffff',
    surfaceAlt: '#faf6ec',
    ink: '#1a2433',
    inkSoft: '#4a5566',
    muted: '#8a8579',
    line: '#e5ddc8',
    primary: '#1e3a5f',
    primaryInk: '#ffffff',
    accent: '#c4302b',
    accentInk: '#ffffff',
    success: '#4a7c59',
    warn: '#d68c1f',
    fieldGreen: '#7fa868',
    fieldDirt: '#c9a875',
    display: 'var(--font-oswald), "Arial Narrow", sans-serif',
    body: 'var(--font-inter), -apple-system, system-ui, sans-serif',
    radius: 10,
  },
  modern: {
    name: 'Modern Minimal',
    bg: '#fafaf9',
    surface: '#ffffff',
    surfaceAlt: '#f5f5f4',
    ink: '#0c0a09',
    inkSoft: '#44403c',
    muted: '#78716c',
    line: '#e7e5e4',
    primary: '#0c0a09',
    primaryInk: '#ffffff',
    accent: '#dc2626',
    accentInk: '#ffffff',
    success: '#16a34a',
    warn: '#ca8a04',
    fieldGreen: '#86a77a',
    fieldDirt: '#d4b896',
    display: 'var(--font-inter), -apple-system, sans-serif',
    body: 'var(--font-inter), -apple-system, system-ui, sans-serif',
    radius: 14,
  },
  diamond: {
    name: 'Diamond Dark',
    bg: '#0f1419',
    surface: '#1a2028',
    surfaceAlt: '#232932',
    ink: '#f0ece4',
    inkSoft: '#c8c0b0',
    muted: '#8a8272',
    line: '#2e343d',
    primary: '#e8d4a2',
    primaryInk: '#0f1419',
    accent: '#e55a3d',
    accentInk: '#ffffff',
    success: '#7fb069',
    warn: '#e8b04a',
    fieldGreen: '#4a7c59',
    fieldDirt: '#8b6f47',
    display: 'var(--font-oswald), "Arial Narrow", sans-serif',
    body: 'var(--font-inter), -apple-system, system-ui, sans-serif',
    radius: 10,
  },
};
