export const THEMES = {
  classic: {
    name: 'Modern Club',
    bg: '#f6f7fb',
    surface: '#ffffff',
    surfaceAlt: '#f8fafc',
    ink: '#111827',
    inkSoft: '#475467',
    muted: '#667085',
    line: '#d9e2ec',
    primary: '#1d4ed8',
    primaryInk: '#ffffff',
    accent: '#f04438',
    accentInk: '#ffffff',
    success: '#12805c',
    warn: '#f59e0b',
    fieldGreen: '#2f9e6d',
    fieldDirt: '#c9975b',
    display: 'var(--font-oswald), "Arial Narrow", sans-serif',
    body: 'var(--font-inter), -apple-system, system-ui, sans-serif',
    radius: 10,
  },
  modern: {
    name: 'Modern Minimal',
    bg: '#f6f7fb',
    surface: '#ffffff',
    surfaceAlt: '#f8fafc',
    ink: '#111827',
    inkSoft: '#475467',
    muted: '#667085',
    line: '#d9e2ec',
    primary: '#111827',
    primaryInk: '#ffffff',
    accent: '#f04438',
    accentInk: '#ffffff',
    success: '#12805c',
    warn: '#f59e0b',
    fieldGreen: '#2f9e6d',
    fieldDirt: '#c9975b',
    display: 'var(--font-inter), -apple-system, sans-serif',
    body: 'var(--font-inter), -apple-system, system-ui, sans-serif',
    radius: 14,
  },
  diamond: {
    name: 'Diamond Dark',
    bg: '#0f1419',
    surface: '#1a2028',
    surfaceAlt: '#232932',
    ink: '#edf2f7',
    inkSoft: '#cbd5e1',
    muted: '#94a3b8',
    line: '#334155',
    primary: '#dbeafe',
    primaryInk: '#0f1419',
    accent: '#f04438',
    accentInk: '#ffffff',
    success: '#22c55e',
    warn: '#f59e0b',
    fieldGreen: '#12805c',
    fieldDirt: '#a16207',
    display: 'var(--font-oswald), "Arial Narrow", sans-serif',
    body: 'var(--font-inter), -apple-system, system-ui, sans-serif',
    radius: 10,
  },
};
